-- generated by write-hypr-theme.sh, don't hand-edit this one
package.loaded["colors-wal"] = nil
package.loaded["colors"] = nil
package.preload["colors-wal.lua"] = function() return require("colors-wal") end
package.preload["colors.lua"] = function() return require("colors-wal") end

local ok, res = pcall(require, "colors-wal")
if not ok then
    local home = os.getenv("HOME") or ""
    local path = home .. "/.config/hypr/colors-wal.lua"
    local f = io.open(path, "r")
    if f then
        f:close()
        return dofile(path)
    end
end
return res
