general {
    hide_cursor = true
    ignore_empty_input = true
    text_trim = true
}

# BACKGROUND
background {
    monitor = 
    # This reads the wallpaper path dynamically from your quickshell cache file
    path = ~/.cache/quickshell-rice/current
    blur_passes = 2
    contrast = 0.8916
    brightness = 0.7172
    vibrancy = 0.1696
    vibrancy_darkness = 0
}

# TIME — 12 HOUR

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%-I")"
    color = rgba(255, 255, 255, 1)

    font_size = 400
    font_family = JetBrains Mono Nerd Font Mono ExtraBold

    shadow_passes = 2
    shadow_size = 3
    shadow_color = rgb(0,0,0)
    shadow_boost = 1.2

    position = -155, -100
    halign = center
    valign = top
}

# MINUTES
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%M")"
    color = rgba(255, 255, 255, 1)

    font_size = 100
    font_family = JetBrains Mono Nerd Font Mono ExtraBold

    position = 40, -217
    halign = center
    valign = top
}

# AM / PM
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%p")"
    color = rgba(255, 255, 255, 1)

    font_size = 32
    font_family = JetBrains Mono Nerd Font Mono ExtraBold

    position = 90,-350
    halign = center
    valign = top
}

# DATE
label {
    monitor =
    text = cmd[update:60000] echo "$(date +"%a, %d %b")"
    color = rgba(255, 255, 255, 1)

    font_size = 10
    font_family = JetBrains Mono Nerd Font Mono ExtraBold

    position = 13, 165
    halign = center
    valign = center
}
