# Screen off after 10 minutes of inactivity
# unless VLC/mpv is playing
listener {
    timeout = 600

    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on

    condition_cmd = ! playerctl --all-players status 2>/dev/null | grep -q '^Playing$'
    condition_retry = 30
}

# Power off after 2 hours of inactivity
# unless VLC/mpv is playing
listener {
    timeout = 7200

    on-timeout = systemctl poweroff

    condition_cmd = ! playerctl --all-players status 2>/dev/null | grep -q '^Playing$'
    condition_retry = 30
}
